export const GET_NODE_ROUTE_REQUEST = 'GET_NODE_ROUTE_REQUEST'
export const GET_NODE_ROUTE_SUCCESS = 'GET_NODE_ROUTE_SUCCESS'
export const GET_NODE_ROUTE_ERROR = 'GET_NODE_ROUTE_ERROR'

export const SET_MAP_CENTER = 'SET_MAP_CENTER'
