export const GET_NODE_ROUTE_REQUEST = 'GET_NODE_ROUTE_REQUEST'
export const GET_NODE_ROUTE_SUCCESS = 'GET_NODE_ROUTE_SUCCESS'
export const GET_NODE_ROUTE_ERROR = 'GET_NODE_ROUTE_ERROR'

export const POST_NODE_REQUEST = 'POST_NODE_REQUEST'
export const POST_NODE_SUCCESS = 'POST_NODE_SUCCESS'
export const POST_NODE_ERROR = 'POST_NODE_ERROR'

export const GET_NODE_REQUEST = 'GET_NODE_REQUEST'
export const GET_NODE_SUCCESS = 'GET_NODE_SUCCESS'
export const GET_NODE_ERROR = 'GET_NODE_ERROR'

export const GET_POLYLINE_REQUEST = 'GET_POLYLINE_REQUEST'
export const GET_POLYLINE_SUCCESS = 'GET_POLYLINE_SUCCESS'
export const GET_POLYLINE_ERROR = 'GET_POLYLINE_ERROR'

export const POST_SEGMENT_REQUEST = 'POST_SEGMENT_REQUEST'
export const POST_SEGMENT_SUCCESS = 'POST_SEGMENT_SUCCESS'
export const POST_SEGMENT_ERROR = 'POST_SEGMENT_ERROR'

export const GET_SEGMENT_REQUEST = 'GET_SEGMENT_REQUEST'
export const GET_SEGMENT_SUCCESS = 'GET_SEGMENT_SUCCESS'
export const GET_SEGMENT_ERROR = 'GET_SEGMENT_ERROR'

export const DELETE_NODE_REQUEST = 'GET_NODE_REQUEST'
export const DELETE_NODE_SUCCESS = 'GET_NODE_SUCCESS'
export const DELETE_NODE_ERROR = 'GET_NODE_ERROR'

export const SET_SEGMENT = 'SET_SEGMENT'

export const SET_MAP_CENTER = 'SET_MAP_CENTER'
