export const GET_NODE_ROUTE_REQUEST = 'GET_NODE_ROUTE_REQUEST'
export const GET_NODE_ROUTE_SUCCESS = 'GET_NODE_ROUTE_SUCCESS'
export const GET_NODE_ROUTE_ERROR = 'GET_NODE_ROUTE_ERROR'

export const POST_NODE_REQUEST = 'POST_NODE_REQUEST'
export const POST_NODE_SUCCESS = 'POST_NODE_SUCCESS'
export const POST_NODE_ERROR = 'POST_NODE_ERROR'

export const GET_NODE_REQUEST = 'GET_NODE_REQUEST'
export const GET_NODE_SUCCESS = 'GET_NODE_SUCCESS'
export const GET_NODE_ERROR = 'GET_NODE_ERROR'

export const SET_MAP_CENTER = 'SET_MAP_CENTER'
